### ISSUE TITLE
Charakterystyka użytkowników systemu

### ISSUE THREAD

**Issue by pkrucz00** [pkrucz00/super-separation-system#11]
Raczej krótkie zadanko - tutaj raczej nie można wielu użytkowników wymyślić. Pewnie użytkowników będzie dwóch, góra trzech- ja, Ty i może prof. Smołka

**Comment by pkrucz00** [comment]
Dopisałem trochę [tutaj](https://docs.google.com/document/d/1EScwDcREVsBKLui22QIh3qMOOHw_ED717lqVT37SlPw/edit) w "scenariuszach użytkowania". Proszę o sprawdzenie, czy to wystarczy, aby zamknąć issue

**Comment by RobertKazimirek** [comment]
Myślę że `Charakterystyka użytkownika systemu` + `Scenariusze użytkowania` w zupełności wystarczą
