### ISSUE TITLE
Podział funkcji z podziałem na aktorów i obszary użycia

### ISSUE THREAD

**Issue by pkrucz00** [pkrucz00/super-separation-system#12]
To jest dokładne wypisanie rzeczy z zadania #3 i pewnie uzupełnione o #11

**Comment by pkrucz00** [comment]
Nie zrobiłem tego per se. Aktorów opisałem. W dokumentacji jest opis interfejsu. Nie łączyłem tego ze sobą. Można zapisać, która flaga w interfejsie konsolowym jest pod którego aktora/historyjkę, ale nie wiem, czy nie jest to przerost formy nad treścią. Oceń to sam @RobertKazimirek

**Comment by RobertKazimirek** [comment]
Myślę, że zastosowanie konkretnych flag widać *intuicyjnie* i nie ma potrzeby tego tłumaczyć, ani przypisywać do historyjek - myślę, że faktycznie byłby to przerost formy nad treścią. Nasz program jest na tyle prosty, że rozbudowa podziału na aktorów byłaby dzieleniem włosa na czworo, a tyle ile mamy, myślę, w zupełności wystarczy.
