### ISSUE TITLE
Opis scenariuszy użytkowania/testowania

### ISSUE THREAD

**Issue by pkrucz00** [pkrucz00/super-separation-system#14]
Przede wszystkim testowania. Trzeba się pobawić w SIR, SDR i inne.

**Comment by pkrucz00** [comment]
**Scenariusze użytkowania** Do sprawdzenia przez Roberta [tutaj](https://docs.google.com/document/d/1EScwDcREVsBKLui22QIh3qMOOHw_ED717lqVT37SlPw/edit) w sekcji "Scenariusze użytkowania"

**Testy** Robert wspomniał o tym w pracy, ja dodałem bibliotekę `museval`. To powinno wystarczyć, ale warto jeszcze opisać, co dane metryki oznaczają

**Comment by RobertKazimirek** [comment]
Bardzo podobają mi się stworzone scenariusze. Myślę, że można zamknąć.
