### ISSUE TITLE
Informacje dotyczące ustalonego zakresu

### ISSUE THREAD

**Issue by pkrucz00** [pkrucz00/super-separation-system#15]
Do zrobienia po analizie ryzyka, żeby zrozumieć, co możemy zrobić w naszej aplikacji.

**Comment by pkrucz00** [comment]
Nie wiem, czy jest sens kontynuować to zadanko, skoro Piętak sam mówił, że na tym etapie możemy jeszcze estymować z MoSCoW. Myślę, że scenariusze i zakres funkcjonalności wystarczająco domkną temat.

Prośba o zgodę na zamknięcie issue

**Comment by RobertKazimirek** [comment]
Pełna zgoda
