### ISSUE TITLE
Model interfejsu użytkownika

### ISSUE THREAD

**Issue by pkrucz00** [pkrucz00/super-separation-system#16]
Opis (może być tekstowy), co nasz użytkownik będzie mógł kliknąć, jak wprowadza wejście, jak dostaje wyjście itd.

**Comment by pkrucz00** [comment]
To samo co tutaj: #17 
Dokument: https://docs.google.com/document/d/1KCL66FCIihlwJ-S1kJhdWmKurjSfkjMfLiNJm3ixTPg/edit

**Comment by RobertKazimirek** [comment]
Jest gites, można zamknąć
