### ISSUE TITLE
Rysunki koncepcyjne

### ISSUE THREAD

**Issue by pkrucz00** [pkrucz00/super-separation-system#17]
Trzeba jakoś zrobić makiety. Co najgorsze - nie mam pojęcia, w jaki sposób to robić XD Znaczy - to jest appka desktopowa, dla webówki jest od groma takich narzędzi, a tutaj to nie wiem, trzeba Piętaka spytać, bo ja wymięknę.

**Comment by pkrucz00** [comment]
Makiety dostępne tutaj: https://docs.google.com/document/d/1KCL66FCIihlwJ-S1kJhdWmKurjSfkjMfLiNJm3ixTPg/edit

**Comment by RobertKazimirek** [comment]
Bardzo mi się podobają, w głowie miałem podobny wygląd naszej apki. Plusik za comic sans xdd
